local plugin = require("cursor_number")
local module = require("cursor_number.module")

describe("parse", function()
  describe("bin", function()
    it("System passed explicit", function()
      assert.are.equal(module.parse("0b0100", 2), 4)
      assert.are.equal(module.parse("0B0110", 2), 6)

      assert.are.equal(module.parse("110", 2), 6)
      assert.are.equal(module.parse("0110", 2), 6)
    end)
    it("System detected", function()
      assert.are.equal(module.parse("0b0100", nil), 4)
      assert.are.equal(module.parse("0B0110", nil), 6)
    end)
    it("Errors", function()
      assert.are.equal(module.parse("0xAB", 2), nil)
      assert.are.equal(module.parse("523", 2), nil)
      assert.are.equal(module.parse("912", 2), nil)
      assert.are.equal(module.parse("0b567", 2), nil)
      assert.are.equal(module.parse("0b567", nil), nil)
    end)
  end)

  describe("oct", function()
    it("System passed explicit", function()
      assert.are.equal(module.parse("0710", 8), 456)
      assert.are.equal(module.parse("710", 8), 456)
      assert.are.equal(module.parse("100", 8), 64)
    end)
    it("System detected", function()
      assert.are.equal(module.parse("0710", nil), 456)
      assert.are.equal(module.parse("0110", nil), 72)
    end)
    it("Errors", function()
      assert.are.equal(module.parse("0xAB", 8), nil)
      assert.are.equal(module.parse("912", 8), nil)
      assert.are.equal(module.parse("0b100", 8), nil)
      assert.are.equal(module.parse("0A", 8), nil)
      assert.are.equal(module.parse("0A", nil), nil)
    end)
  end)

  describe("hex", function()
    it("System passed explicit", function()
      assert.are.equal(module.parse("0x4F", 16), 79)
      assert.are.equal(module.parse("0x4A", 16), 74)
      assert.are.equal(module.parse("4A", 16), 74)
      assert.are.equal(module.parse("110", 16), 272)
      assert.are.equal(module.parse("0800", 16), 2048)
      assert.are.equal(module.parse("0b100", 16), 45312)
    end)
    it("System detected", function()
      assert.are.equal(module.parse("0x4F", nil), 79)
      assert.are.equal(module.parse("0X4A", nil), 74)
    end)
    it("Errors", function()
      assert.are.equal(module.parse("0xFGH", 16), nil)
    end)
  end)

  it("dec", function()
    assert.are.equal(module.parse("123", 10), 123)
    assert.are.equal(module.parse("123", nil), 123)
    assert.are.equal(module.parse("100", nil), 100)
  end)
end)

describe("convert", function()
  it("dec", function()
    assert.are.same(module.convert(123),
      {
        "dec: 123",
        "bin: 1111011",
        "oct: 173",
        "hex: 7b"
      }
    )
  end)
end)
